Sharan_StudentProject_aug19/Sharan_StudentProject_aug19/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Sharan_StudentProject_aug19.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Sharan_StudentProject_aug19.Controllers
{
    public class StudentController : Controller
    {
        public static List<Student> _students = new List<Student>
        {
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "ANJU",
                StudLastName = "PAUL",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud1@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "BTech",
                StudStream = "CSE"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "KARTHIK",
                StudLastName = "KULKARNI",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud2@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "MTech",
                StudStream = "ECE"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "GUMMIREDDY",
                StudLastName = "SUNEETHI",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud3@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "MTech",
                StudStream = "CSE"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "Sandeep",
                StudLastName = "Varma",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud4@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "BBA",
                StudStream = "Finance"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "NEHA",
                StudLastName = "NEHA",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud5@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "MBA",
                StudStream = "HR"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "GEETHU",
                StudLastName = "S",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud6@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "MBA",
                StudStream = "Finance"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "SAHANA",
                StudLastName = "SAHANA",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud7@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "BTech",
                StudStream = "EEE"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "CHAITRA",
                StudLastName = "RAO",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud8@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "MTech",
                StudStream = "EEE"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "LOKESH",
                StudLastName = "M",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud9@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "MTech",
                StudStream = "ECE"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "NISHANT",
                StudLastName = "PATIL",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud10@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "MTech",
                StudStream = "CSE"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "VARSHA",
                StudLastName = "V",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud11@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "MBA",
                StudStream = "HR"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "SACHIN",
                StudLastName = "K",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud12@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "BTech",
                StudStream = "CSE"
            },
            new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = "KUSHAL",
                StudLastName = "M",
                StudPhone = 1234567890,
                StudDob = new DateTime(2020,08,21).Date,
                StudAddress = "Ground Floor, ‘A’ wing, Divyasree Chambers, # 11, O’Shaughnessy Road, Langford Gardens,Bengaluru 560025",
                StudEmail = "stud13@gmail.com",
                StudDoj = new DateTime(2022,08,21).Date,
                StudCourse = "MTech",
                StudStream = "ECE"
            },
        };

        public IActionResult displayStudents()
        {
            ViewBag.studList = _students;
            return View();
        }

        public IActionResult addStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult addStudent(Student input)
        {
            _students.Add(new Student()
            {
                StudId = Guid.NewGuid(),
                StudFirstName = input.StudFirstName,
                StudLastName = input.StudLastName,
                StudDob = input.StudDob,
                StudAddress = input.StudAddress,
                StudEmail = input.StudEmail,
                StudDoj = input.StudDoj,
                StudCourse = input.StudCourse,
                StudStream = input.StudStream,
            });
            return RedirectToAction("displayStudents");
        }

        public IActionResult deleteStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult deleteStudent(Guid id)
        {
            _students.Remove(_students.SingleOrDefault(x => x.StudId == id));
            return RedirectToAction("displayStudents");
        }

        public IActionResult searchStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult searchStudent(Guid id)
        {
            ViewBag.student = _students.SingleOrDefault(x => x.StudId == id);
            return View();
        }

        [HttpGet]
        public ActionResult modifyStudent(Guid id)
        {
            return View(_students.SingleOrDefault(x => x.StudId == id));
        }

        [HttpPost]
        public ActionResult modifyStudent(Student std)
        {
            var student = _students.Where(x => x.StudId == std.StudId).SingleOrDefault();
            if (std.StudFirstName != null && student.StudFirstName != null) { student.StudFirstName = std.StudFirstName; }

Sharan_StudentProject_aug19/Sharan_StudentProject_aug19/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sharan_StudentProject_aug19</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Student Form</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="addStudent">Add Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="searchStudent">Search Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="displayStudents">Student List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Student Form
            <span style="float:right">@DateTime.Now.TimeOfDay.Hours : @DateTime.Now.TimeOfDay.Minutes</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>